# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      git clone --mirror "https://yicxie2017@gmail.com:$(199138Xx!)@dev.azure.com/yicxie2017/_git/DL4NLP"    
      cd DL4NLP.git	
      git remote add --mirror=fetch secondary "https://Xieyichen:$(199138Xx)@github.com/Xieyichen/DL4NLP.git"
      git fetch origin
      git push secondary --all
